; ============================================================
;  PlatformIO Project Configuration – SmartWaterChick ESP32
; ============================================================
[env:esp32dev]
platform  = espressif32
board     = esp32doit-devkit-v1
framework = arduino

; ---- Upload & Monitor ----
monitor_speed  = 115200
upload_speed   = 115200
upload_port    = COM6

; ---- Library Dependencies ----
lib_deps =
    https://github.com/mobizt/Firebase-ESP-Client.git
    https://github.com/johnrickman/LiquidCrystal_I2C.git
