; ============================================================
; platformio.ini — Konfigurasi PlatformIO untuk Smart Water Chick
; Upload via: PlatformIO (VS Code Extension)
; Board: ESP32 Dev Module
; ============================================================

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv

; Kecepatan baud untuk Serial Monitor
monitor_speed = 115200
upload_speed = 115200

; Library yang digunakan
lib_deps = 
    ; Firebase ESP Client — koneksi ke Firebase Realtime Database
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.14
    ; DHT Sensor Library — baca suhu & kelembaban
    adafruit/DHT sensor library@^1.4.4
    ; Adafruit Unified Sensor — dependensi DHT
    adafruit/Adafruit Unified Sensor@^1.1.14
    ; NTPClient — untuk mendapatkan waktu internet (tanggal/jam)
    arduino-libraries/NTPClient@^3.2.1
    ; Library untuk LCD I2C
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

; Opsi build
build_flags = 
    -DCORE_DEBUG_LEVEL=1
